### PR TITLE
Feature/tg 29

### PR DESCRIPTION
**Pull request by ivanStarikov**
This change is [Reviewable](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1)

### CODE REVIEW

**Review by ivanStarikov — COMMENTED** [review]
> Reviewed 1 of 32 files at r1, 38 of 85 files at r3.
> *[Reviewable](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1)* status: 39 of 59 files reviewed, 6 unresolved discussions

___
*[LICENSE, line 0 at r3](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1#-LXs__iQ3XP8VIpfYnDy:-LXs__iQ3XP8VIpfYnDz:b-oobvea) ([raw file](https://github.com/traningcenter2018-2019/a_d_ilyina_first_task/blob/81dc55bde5170fa289c05db5359f0db342bd6fd8/LICENSE#L0)):*
Лицензию вернуть
___
*[src/main/java/netcracker/practice/crossgen/Main.java, line 17 at r3](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1#-LXs_nv22iAuNC69GAeH:-LXs_nv22iAuNC69GAeI:br6daux) ([raw file](https://github.com/traningcenter2018-2019/a_d_ilyina_first_task/blob/81dc55bde5170fa289c05db5359f0db342bd6fd8/src/main/java/netcracker/practice/crossgen/Main.java#L17)):*
> ```Java
>             gt.start();
>         } catch (IOException e) {
>             e.printStackTrace();
> ```

использовать slf4j как логгер. С настройкой уровней логирования. Взять что нибудь типа sl4j-simple jar
___
*[src/main/java/netcracker/practice/crossgen/Settings.java, line 15 at r3](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1#-LXsaE0H8syqsxdLJy4n:-LXsaE0H8syqsxdLJy4o:b-s6n1v6) ([raw file](https://github.com/traningcenter2018-2019/a_d_ilyina_first_task/blob/81dc55bde5170fa289c05db5359f0db342bd6fd8/src/main/java/netcracker/practice/crossgen/Settings.java#L15)):*
> ```Java
>      */
>     long GENERATION_TIMEOUT = 1000;
> ```

А чем вызвано использование package private уровня доступа?
___
*[src/main/java/netcracker/practice/crossgen/cli/dispatcher/CrosswordCommandDispatcher.java, line 16 at r3](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1#-LXsbORC7qjXrSgJg2_k:-LXsbORC7qjXrSgJg2_l:bfg4d1n) ([raw file](https://github.com/traningcenter2018-2019/a_d_ilyina_first_task/blob/81dc55bde5170fa289c05db5359f0db342bd6fd8/src/main/java/netcracker/practice/crossgen/cli/dispatcher/CrosswordCommandDispatcher.java#L16)):*
> ```Java
>         add(new SaveCommand());
>         add(new HelpCommand());
>         add(new QuitCommand());
> ```

В целом это место рефлексивно могла собрать, но и так пойдет
___
*[src/main/java/netcracker/practice/crossgen/game/CrosswordGame.java, line 38 at r3](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1#-LXsblij7vam8maxsm9w:-LXsblij7vam8maxsm9x:b-v3lijr) ([raw file](https://github.com/traningcenter2018-2019/a_d_ilyina_first_task/blob/81dc55bde5170fa289c05db5359f0db342bd6fd8/src/main/java/netcracker/practice/crossgen/game/CrosswordGame.java#L38)):*
> ```Java
>             );
>             ((CrosswordConfiguration) config).setClues(
>                 "лис: Хитрый зверь.\n" +
> ```

А почему это не тест? Дебажила много?
___
*[src/main/java/netcracker/practice/crossgen/game/Game.java, line 21 at r3](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1#-LXsbud4-r6eWTZkJDJR:-LXsbud4-r6eWTZkJDJS:b-dgf0n9) ([raw file](https://github.com/traningcenter2018-2019/a_d_ilyina_first_task/blob/81dc55bde5170fa289c05db5359f0db342bd6fd8/src/main/java/netcracker/practice/crossgen/game/Game.java#L21)):*
> ```Java
>     void setGenerator(Generator generator);
>     void setState(GameState state);
>     void subscribe(GameObserver observer);
> ```

откуда такая любовь к package private?

**Review by ivanStarikov — COMMENTED** [review]
> Reviewed 20 of 85 files at r3.
> *[Reviewable](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1)* status: all files reviewed, 6 unresolved discussions

**Review by ivanStarikov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1)* status: all files reviewed, 8 unresolved discussions

___
*[src/test/java/netcracker/practice/crossgen/logic/generator/DenseGeneratorTest.java, line 20 at r3](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1#-LXscwex1vIvvgIkUzcH:-LXscwex1vIvvgIkUzcI:b-pijxyw) ([raw file](https://github.com/traningcenter2018-2019/a_d_ilyina_first_task/blob/81dc55bde5170fa289c05db5359f0db342bd6fd8/src/test/java/netcracker/practice/crossgen/logic/generator/DenseGeneratorTest.java#L20)):*
> ```Java
> public class DenseGeneratorTest {
> 
>     private final Logger log = Logger.getLogger(StraightAngleTest.class.getName());
> ```

Возьми нормальный логгер. slf4j
___
*[src/test/java/netcracker/practice/crossgen/logic/generator/DenseGeneratorTest.java, line 101 at r3](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1#-LXsciXF57IhObU8n-Yd:-LXsciXF57IhObU8n-Ye:b-sigroy) ([raw file](https://github.com/traningcenter2018-2019/a_d_ilyina_first_task/blob/81dc55bde5170fa289c05db5359f0db342bd6fd8/src/test/java/netcracker/practice/crossgen/logic/generator/DenseGeneratorTest.java#L101)):*
> ```Java
>     public void testSingleGeneration() {
>         CanadianCrossword genCrossword = gen.generate();
> ```

А что проверяет этот тест? Ты неплохо готовишь данные, но ни одного asserts эти тесты всегда зеленые

**Review by ussur — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1#-:-LXsrtG86twfZxw8NamK:bnfp4nl)* status: 0 of 6 files reviewed, 8 unresolved discussions (waiting on @ivanStarikov)

___
*[src/test/java/netcracker/practice/crossgen/logic/generator/DenseGeneratorTest.java, line 20 at r3](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1#-LXscwex1vIvvgIkUzcH:-LXss15r91tCxBEv5hfd:bnbs7zn) ([raw file](https://github.com/traningcenter2018-2019/a_d_ilyina_first_task/blob/81dc55bde5170fa289c05db5359f0db342bd6fd8/src/test/java/netcracker/practice/crossgen/logic/generator/DenseGeneratorTest.java#L20)):*
<details><summary><i>Previously, ivanStarikov wrote…</i></summary><blockquote>

Возьми нормальный логгер. slf4j
</blockquote></details>

Сделано
___
*[src/test/java/netcracker/practice/crossgen/logic/generator/DenseGeneratorTest.java, line 101 at r3](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1#-LXsciXF57IhObU8n-Yd:-LXsrE1c3dbHWEW690vE:b-894rx) ([raw file](https://github.com/traningcenter2018-2019/a_d_ilyina_first_task/blob/81dc55bde5170fa289c05db5359f0db342bd6fd8/src/test/java/netcracker/practice/crossgen/logic/generator/DenseGeneratorTest.java#L101)):*
<details><summary><i>Previously, ivanStarikov wrote…</i></summary><blockquote>

А что проверяет этот тест? Ты неплохо готовишь данные, но ни одного asserts эти тесты всегда зеленые
</blockquote></details>

По хорошему, это даже не юнит тесты, так как в них нет ожидаемого результата. Генератор может вернуть любой кроссворд, поэтому я написала тесты, чтобы посмотреть, как он работает и какие результаты возвращает
___
*[LICENSE, line  at r3](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1#-LXs__iQ3XP8VIpfYnDy:-LXseyPDEeFLcQqQ_GAO:bnbs7zn) ([raw file](https://github.com/traningcenter2018-2019/a_d_ilyina_first_task/blob/81dc55bde5170fa289c05db5359f0db342bd6fd8/LICENSE#L)):*
<details><summary><i>Previously, ivanStarikov wrote…</i></summary><blockquote>

Лицензию вернуть
</blockquote></details>

Сделано
___
*[src/main/java/netcracker/practice/crossgen/Main.java, line 17 at r3](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1#-LXs_nv22iAuNC69GAeH:-LXsoKtO7AOnVe-s449U:b-ak1aov) ([raw file](https://github.com/traningcenter2018-2019/a_d_ilyina_first_task/blob/81dc55bde5170fa289c05db5359f0db342bd6fd8/src/main/java/netcracker/practice/crossgen/Main.java#L17)):*
<details><summary><i>Previously, ivanStarikov wrote…</i></summary><blockquote>

использовать slf4j как логгер. С настройкой уровней логирования. Взять что нибудь типа sl4j-simple jar
</blockquote></details>

Добавила slf4j, уровни логирования настраиваются в simplelogger.properties
___
*[src/main/java/netcracker/practice/crossgen/Settings.java, line 15 at r3](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1#-LXsaE0H8syqsxdLJy4n:-LXsqAMn7F-6dkJgmo-6:b-umrry1) ([raw file](https://github.com/traningcenter2018-2019/a_d_ilyina_first_task/blob/81dc55bde5170fa289c05db5359f0db342bd6fd8/src/main/java/netcracker/practice/crossgen/Settings.java#L15)):*
<details><summary><i>Previously, ivanStarikov wrote…</i></summary><blockquote>

А чем вызвано использование package private уровня доступа?
</blockquote></details>

Это интерфейс, уровни доступа к полям по умолчанию public
___
*[src/main/java/netcracker/practice/crossgen/game/CrosswordGame.java, line 38 at r3](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1#-LXsblij7vam8maxsm9w:-LXsqizl993RAgaFz2Hg:bs0vxi0) ([raw file](https://github.com/traningcenter2018-2019/a_d_ilyina_first_task/blob/81dc55bde5170fa289c05db5359f0db342bd6fd8/src/main/java/netcracker/practice/crossgen/game/CrosswordGame.java#L38)):*
<details><summary><i>Previously, ivanStarikov wrote…</i></summary><blockquote>

А почему это не тест? Дебажила много?
</blockquote></details>

Да, и сначала много изменений вносила, тесты бы пришлось переписывать
___
*[src/main/java/netcracker/practice/crossgen/game/Game.java, line 21 at r3](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1#-LXsbud4-r6eWTZkJDJR:-LXsr9DkD4iSGJpMOgzA:b-4hpr3v) ([raw file](https://github.com/traningcenter2018-2019/a_d_ilyina_first_task/blob/81dc55bde5170fa289c05db5359f0db342bd6fd8/src/main/java/netcracker/practice/crossgen/game/Game.java#L21)):*
<details><summary><i>Previously, ivanStarikov wrote…</i></summary><blockquote>

откуда такая любовь к package private?
</blockquote></details>

Это интерфейс

**Review by ussur — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1)* status: 0 of 6 files reviewed, 8 unresolved discussions (waiting on @ivanStarikov)

___
*[src/main/java/netcracker/practice/crossgen/cli/dispatcher/CrosswordCommandDispatcher.java, line 16 at r3](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1#-LXsbORC7qjXrSgJg2_k:-LXsypZ1AXqSPntHTa-x:b-24u4bd) ([raw file](https://github.com/traningcenter2018-2019/a_d_ilyina_first_task/blob/81dc55bde5170fa289c05db5359f0db342bd6fd8/src/main/java/netcracker/practice/crossgen/cli/dispatcher/CrosswordCommandDispatcher.java#L16)):*
<details><summary><i>Previously, ivanStarikov wrote…</i></summary><blockquote>

В целом это место рефлексивно могла собрать, но и так пойдет
</blockquote></details>

У рефлексии есть минусы, я решила, что здесь она будет лишней

**Review by ivanStarikov — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 11 of 12 files at r8.
> *[Reviewable](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @ivanStarikov)

**Review by ivanStarikov — COMMENTED** [review]
> Reviewed 1 of 12 files at r8.
> *[Reviewable](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @ivanStarikov)

**Review by ivanStarikov — COMMENTED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/traningcenter2018-2019/a_d_ilyina_first_task/1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
